% Get output filename routine
function [filename,parentDir] = getOutputFilename( ...
    audioFilename, HRTF, ensembleActualWidth, elevation, azimuthOffset, ...
    iRep) 

    filename = sprintf("%s_hrtf%d_%s_width%.2f_el%.2f_azoffset%.2f_iteration%d", ...
        audioFilename.name, ...
        HRTF.Id, ...
        HRTF.HRTFGroup, ...
        ensembleActualWidth, ...
        elevation, ...
        azimuthOffset, ...
        iRep);
end
