clear
close all

maes = [
    8.02, ...
    7.79, ...
    7.39, ...
    7.24, ...
    6.77, ...
    6.69, ...
    6.63, ...
    ];
stds = [
    0.07, ...
    0.09, ...
    0.03, ...
    0.11, ...
    0.12, ...
    0.16, ...
    0.12, ...
    ];
features = categorical({ ...
    'IC', ...
    'ITD', ...
    'ITD+IC', ...
    'ILD', ...
    'ILD+IC', ...
    'ILD+ITD', ...
    'ILD+ITD+IC', ...
    });
features = reordercats(features, cellstr(features)');

f = figure;
f.Position(3:4) = [500 400];

b=bar(features,maes);

hold on
er = errorbar(features,maes,stds,stds);
er.Color = [0 0 0];
er.LineStyle = 'none';
hold off

maetooltips = repmat('°', length(maes), 1);
maetooltips = [num2str(maes'), maetooltips];

stdtooltips = repmat('±', length(stds), 1);
stdtooltips = [stdtooltips, num2str(stds')];
stdtooltips = [stdtooltips, repmat('°', length(stds), 1)];

tooltips = [maetooltips, repmat(newline, length(maes), 1), stdtooltips];

text(1:length(maes), maes + stds, tooltips, ...
    'vert','bottom', ...
    'horiz','center');

ylim([6.5, 8.5])
xlabel('Features')
ylabel('Mean Absolute Error')
ytickformat('%g°')

ax = gca;
ax.XGrid = 'off';
ax.YGrid = 'on';

exportgraphics(f, 'imgs/mae_vs_features.png', ...
    Resolution=300)
